# Generated by Django 4.1 on 2022-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='imageURI',
            field=models.TextField(default='random'),
            preserve_default=False,
        ),
    ]
