# Generated by Django 4.1.1 on 2022-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('JS', 'JAVASCRIPT'), ('RC', 'REACT'), ('RCN', 'REACT NATIVE'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SASS', 'SASS'), ('PY', 'PYTHON'), ('DJ', 'DJANGO'), ('DJR', 'DJANGO REST')], default='JS', max_length=4),
            preserve_default=False,
        ),
    ]
